name: Deploy secrets to docker swarm

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: ghcr.io/progwise/george-ai
  HOST: 82.165.141.156
  SSH_USER: swarm

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/establish-ssh
        id: ssh
        with:
          target-host: ${{ env.HOST }}
          target-user: ${{ env.SSH_USER }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
      - name: List remote host docker secrets
        run: |
          ${{ steps.ssh.outputs.cmd}} "docker secret ls"
