name: Deploy Caddy to docker swarm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  HOST: 82.165.141.156
  SSH_USER: swarm

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/establish-ssh
        id: ssh
        with:
          target-host: ${{ env.HOST }}
          target-user: ${{ env.SSH_USER }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
      - name: Copy swarm stack file
        run: |
          echo "Copy stack file"
          scp -i ~/.ssh/id_rsa ./.deploy/caddy-stack.yml swarm@${{ env.HOST }}:/home/swarm/caddy-stack.yml
      - name: Run deployment script
        run: |
          echo "Deploying to production server"
          ssh -i ~/.ssh/id_rsa swarm@${{ env.HOST }} << EOF
            docker stack deploy --compose-file /home/swarm/caddy-stack.yml caddy
          EOF
