name: Deploy George-AI to docker swarm

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: ghcr.io/progwise/george-ai
  HOST: 82.165.141.156
  SSH_USER: swarm

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/establish-ssh
        id: ssh
        with:
          target-host: ${{ env.HOST }}
          target-user: ${{ env.SSH_USER }}
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
      - name: generate george-ai container env files
        run: |
          ssh -i ~/.ssh/id_rsa swarm@${{ env.HOST }} << EOF
            echo "POSTGRES_PASSWORD=${{ secrets.KEYCLOAK_POSTGRES_PASSWORD}}" >./gai-keycloak-db.env
            echo "KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD}}" >./gai-keycloak.env
            echo "KC_DB_PASSWORD=${{ secrets.KEYCLOAK_POSTGRES_PASSWORD}}" >>./gai-keycloak.env
            echo "TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY}}" >./gai-typesense.env
            echo "TYPESENSE_API_KEY=${{ secrets.TYPESENSE_API_KEY}}" >./gai-backend.env
            echo "DATABASE_URL=postgresql://chatweb:${{ secrets.GAI_DB_PASSWORD}}@gai-db:5432/chatweb?schema=public" >>./gai-backend.env
            echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY}}" >>./gai-backend.env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY}}" >>./gai-backend.env
            echo "GRAPHQL_API_KEY=${{ secrets.GRAPHQL_API_KEY}}" >>./gai-backend.env
            echo "POSTGRES_PASSWORD=${{ secrets.GAI_DB_PASSWORD}}" >./gai-db.env
            echo "GRAPHQL_API_KEY=${{ secrets.GRAPHQL_API_KEY}}" >./gai-chatweb.env
            echo "GOOGLE_DRIVE_CLIENT_ID=${{ secrets.GOOGLE_DRIVE_CLIENT_ID}}" >>./gai-chatweb.env
            echo "GOOGLE_DRIVE_CLIENT_SECRET=${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET}}" >>./gai-chatweb.env
          EOF
      - name: Copy swarm stack file
        run: |
          echo "Copy stack file"
          scp -i ~/.ssh/id_rsa ./.deploy/george-ai-stack.yml swarm@${{ env.HOST }}:/home/swarm/george-ai-stack.yml
      - name: Run deployment script
        run: |
          echo "Deploying to production server"
          ssh -i ~/.ssh/id_rsa swarm@${{ env.HOST }} << EOF
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io/progwise -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/progwise/george-ai/chat-web:latest
            docker pull ghcr.io/progwise/george-ai/backend:latest
            docker pull ghcr.io/progwise/george-ai/pocketbase:latest
            docker stack deploy --with-registry-auth --compose-file /home/swarm/george-ai-stack.yml george-ai
          EOF
