name: Discord Notification

on:
  push:
    # branches:
    #   - main

jobs:
  discord:
    runs-on: ubuntu-22.04
    steps:
      - name: 'send message'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '**{{ EVENT_PAYLOAD.sender.login }}** has deployed **${{ github.event.head_commit.message }}** on production ðŸŽ‰'
